### ISSUE TITLE
memz is broken

### ISSUE THREAD

**Issue by protogenraymond** [parabirb/sus93-repo#13]
the memz module isn't working, either busybody needs to fix it or it needs to be removed

**Comment by Busybody64** [comment]
Oops

I was wondering how to fix it myself, honestly.
I thought parabirb was going to fix it!

**Comment by protogenraymond** [comment]
ill keep this open until parabirb closes it or its fixed, it causes an error as soon as its installed

**Comment by Busybody64** [comment]
What does the error say?

**Comment by parabirb** [comment]
will fix once there's confirmation of what the error is

**Comment by protogenraymond** [comment]
![image](https://user-images.githubusercontent.com/82468210/136721463-9f19c809-b56e-4f68-98fe-db32bf0a8dfc.png)
this is the error; this was produced by the cli system, but it happens when installed by the gui as well (since it uses the same system, you can literally open a terminal window and watch it install)

**Comment by parabirb** [comment]
yea it's a syntax error i'll fix it later

**Comment by protogenraymond** [comment]
you can fix the bug by removing the last `}` in the code

**Comment by parabirb** [comment]
will wait for busybody to fix it and reopen if further issues arise
