### ISSUE TITLE
Trollbox.party and cyio.trollbox.party in windows 93

### ISSUE THREAD

**Issue by Busybody64** [parabirb/sus93-repo#7]
https://github.com/Busybody64/Sus93-TrollboxParty
https://github.com/Busybody64/Sus93-CyioTrollboxParty

The first one doesn't quite work for some reason, but we should keep it anyways, because it might be a bug with the SITE instead of the package itself.

The second one works just fine!

**Comment by Busybody64** [comment]
thx!

**Comment by parabirb** [comment]
merged
